apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  namespace: hellow
spec:
  project: default
  source:
    repoURL: https://github.com/marinamagaldi/gitops.git
    path: mychart
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: hellow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
