app:
  image: 371663a17f27a55f8638f4024ca209029e72ffce
    repository: docker.io/marinamagaldib/fastapi-app
    tag: "latest"
  replicas: 2
  containerPort: 8000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000