---
app:
  image: cea28b35e99eb602af1a62565e7bc805b35d0b65
    repository: docker.io/marinamagaldib/fastapi-app
    tag: {{ github.sha }}
  replicas: 2
  containerPort: 8000
service:
  type: ClusterIP
  port: 80
  targetPort: 8000